In [1]:
import numpy as np

**Question** - Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.


In [18]:
def pow_mat(arr, pow_level=4, increasing = True):
  if increasing:
    return np.column_stack([arr**i for i in range(pow_level)])
  else:
    return np.column_stack([arr**(pow_level - i - 1) for i in range(pow_level)])

#Test case
input_vec = np.array([1,2,3,5])
power_level = 4
print(pow_mat(input_vec, power_level, increasing = True))    
print(pow_mat(input_vec, power_level, increasing = False))    

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


**Question**: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [16]:
def moving_average(arr, window = 3):
  arr_list = []
  for i in range(len(arr)-(window-1)):
    subset_mean = np.average(arr[i:i+window])
    arr_list.append(subset_mean)
  return np.array(arr_list).round(2)

#Test case 1
test_array = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
print(moving_average(test_array,3))


#Test case 2
test_array2 = np.array([10,20, 30, 40, 50, 60, 70, 80, 90, 100])
print(moving_average(test_array2,4))


[  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]
[25. 35. 45. 55. 65. 75. 85.]
